# Generated by Django 5.0.3 on 2024-06-14 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='articles/media'),
        ),
        migrations.AlterField(
            model_name='missions',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='articles/media'),
        ),
    ]
