# Generated by Django 5.0.3 on 2024-12-23 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savemission',
            old_name='Mission',
            new_name='mission',
        ),
        migrations.RenameField(
            model_name='savemission',
            old_name='User',
            new_name='user',
        ),
    ]
